name: ci workflow
on:
  # push:
  #   branches:
  #     - "main"

  # pull_request:
  #   branches:
  #     - "feature"
  #   types: [opend, closed]
  
  # schedule:
  #   - cron: "0/5 * * * *"

  repository_dispatch:
    types: [test]

  workflow_dispatch:
    inputs:
      versionName:
        required: true
        description: "this is version name for github workflow"  

jobs:
  ci-workflow:
    name: ci workflow
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v3

      - name: build the app
        run: "mvn clean package"
        shell: bash

      - name: test the app
        run: "mvn test"
        shell: bash
